# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt || echo "No requirements.txt"
  displayName: 'Install dependencies'

- script: |
    python app.py
  displayName: 'Run Python Script'

- script: |
    # Build the package
    python setup.py sdist bdist_wheel
  displayName: 'Build Package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'  # Publish the dist directory
    ArtifactName: 'PythonAppArtifacts'
    publishLocation: 'Container'
    
- task: AzureCLI@2
  inputs:
    azureSubscription: '<your-azure-subscription>' # Specify your Azure service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az artifacts universal publish \
        --feed s3cloudhub0666 \
        --name your-package-name \
        --version 0.1 \
        --description "Your package description" \
        --path $(System.DefaultWorkingDirectory)/dist
